// step114: now lets try to make the schema for books now here below.
import mongoose from "mongoose";

// step115: lets create the schema first here below.
const bookSchema = new mongoose.Schema({
    // step117: so each book will have a title now here below.
    title: {
        type: String,
        required: true
    },
    // step118: also each book will have a caption, thus here below.
    caption: {
        type: String,
        required: true
    },
    // step119: also each book will have an image, thus here below.
    image: {
        type: String,
        required: true
    },
    // step120: similarly there will be rating, which will be Number type, thus here below.
    rating: {
        type: Number,
        required: true,
        // step121: it can be minimum "1" and maximum "5", thus here below.
        min: 1,
        max: 5
    },

    // step122: finally, we will also have owner of the post, thus here below.
    user: {
        // step123: This means the value stored here will be ObjectId, i.e., the unique ID generated by MongoDB for documents.
        type: mongoose.Schema.Types.ObjectId,

        // step124: This tells Mongoose that this ObjectId refers to a document in the User collection, so that it can fetch the details of the user who created the post from there, thus here below.
        ref: "User",
        required: true
    }
    
    // step116: each book will have the created at and updated at times, so lets have for that the timestamps object here below, which will be used to have the created_at and updated_at fields for each document in mongoDB there too, whenever a book document is created based on this above schema, thus here below.
}, {timestamps: true})

// step125: now as usual, we now create the model based on the above schema, so that using the Model we will be able to interact with the database like "insert, create, find, update, delete" the data in the database, thus here below.
const Book = mongoose.model("Book", bookSchema);

// step126: now lets export this Book model so that it can be used in other files ; and now we will be using it in toher files whenever we will want to interact with the Book model, thus here below.

// step127: see the next steps in bookRoutes.js file now there.
export default Book